# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15awdbck4zIyPoE42QEM9EcOOBoXxtH3x
"""

import numpy as np 
import pandas as pd

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.utils import resample
import seaborn as sb

df=pd.read_csv("/content/spam.csv",encoding="latin1")
df

df.info()

df.isnull().sum()

x=df.v2
x

y=df.v1
y

y.replace(to_replace='ham',value=1,inplace=True)
y.replace(to_replace='spam',value=0,inplace=True)
y

y=df.v1
y.value_counts()

sb.histplot(y)

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.9,random_state=25)

gok= pd.concat([x_train, y_train], axis=1)

# separate minority and majority classes
spam = gok[gok.v1==0]
ham = gok[gok.v1==1]